### ISSUE TITLE
v1.0.4 introduces NimBLE dependency, breaking BlueDroid-based projects

### ISSUE THREAD

**Issue by microbotsio** [gb88/BLEOTA#26]
Hi Giovanni,

Thanks again for BLEOTA and for adding Arduino Library Manager support. While testing integration as a dependency for our ProtoBot library, I noticed a packaging/versioning issue that may affect users installing through Arduino Library Manager.

From the release notes:

-  v1.0.3: “Support only BlueDroid”
-  v1.0.4: “Support last version of Nimble”

Our existing code uses the classic BLEDevice / Bluedroid API, so v1.0.3 works well. However, upgrading to v1.0.4 breaks compatibility unless the project is migrated to NimBLE. The concern is that, even if a dependent library pins BLEOTA to v1.0.3, users may still update BLEOTA via the Arduino IDE update prompt and unintentionally install v1.0.4, which changes compatibility.

Would you consider keeping the current BLEDevice / Bluedroid version as the main BLEOTA release line, and publishing the NimBLE version as a separate library/repo (e.g. BLEOTA_NimBLE)? I noticed you already have a separate branch for it. Keeping them separate would ensure that both the Bluedroid and NimBLE versions remain compatible in their latest releases, especially since Arduino Library Manager always installs the newest version and doesn’t reliably support selecting specific versions.

I believe this would make Arduino Library Manager usage much safer and clearer for end users.

Thanks again.
Carl

**Comment by gb88** [comment]
Hi Carl, I don't understand why the compatibility is broken, since I keep the source file for NimBLE separate. What happens in case of an update? I put everything together to maintain the same codebase and avoid managing two different repositories.

**Comment by microbotsio** [comment]
Hi Giovanni,

Thanks for the clarification - that makes sense from a repo/maintenance point of view. From what I’m seeing, the issue isn’t where the NimBLE code lives, but with what the API expose to the user between releases.

With v1.0.3, my existing code compiles without any changes using:

```
#include <BLEOTA.h>
BLEOTA.begin(bleServer);
BLEOTA.process();
```

After updating to v1.0.4, the same code fails with: 'BLEOTA' was not declared in this scope

So BLEOTA is no longer available in the same way. Even though NimBLE is in a separate source file, the compiled result ends up exposing a different interface depending on the version.

This becomes an issue specifically with Arduino Library Manager, because users typically install the latest version automatically. So an update from 1.0.3 → 1.0.4 can break compilation in existing BlueDroid-based projects without any code changes - That’s what makes it 'uncompatible' even if internally the codebase is shared.

Hope that clarifies what I’m seeing on my side.

**Comment by gb88** [comment]
I understand now but to keep the compatibility 1 line of code must be added, just declare BLEOTAClass BLEOTA; in the code

**Comment by microbotsio** [comment]
Hi Giovanni,

Thanks a lot for looking into this and for the clarification, really appreciate it! 🙂

We’ve tested again with the latest v1.0.5 and we’re still running into an issue when compiling BlueDroid-based projects. Specifically, we’re getting:

```
NimBLEDevice.h: No such file or directory
    5 | #include <NimBLEDevice.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
exit status 1

Compilation error: exit status 1

```

It looks like the NimBLE header is still being included even when using the standard BLE (BlueDroid) setup. Would it be possible to avoid including `NimBLEDevice.h` unless the NimBLE implementation is explicitly used? If not you can maybe use a compile-time flag like:

```
#ifdef USE_NIMBLE
  #include <NimBLEDevice.h>
#else
  #include <BLEDevice.h>
#endif
```

and only enabling `USE_NIMBLE` when needed. Another possible workaround would be to list NimBLE as a dependency in library.properties so Arduino installs it automatically, but I think the better fix would be to keep the NimBLE include isolated to the NimBLE-specific source files so BlueDroid projects don’t require it unnecessarily. Alternatively, this might also be resolved by including the header only in the NimBLE source files rather than globally 

Thanks again for your help on this!

**Comment by gb88** [comment]
Which version of esp32-arduino you use?

**Comment by microbotsio** [comment]
Hi Giovanni,

We are using the Arduino IDE v2.3.5
ESP32 package v3.3.8 (latest)
